### ISSUE TITLE
Arrumar cadastro (Selecionar um tipo de perfil)

### ISSUE THREAD

**Issue by caue96** [fga-gpp-mds/2016.2-Observatorio-de-Residuos-Frontend#69]
Aconteceu algo durante esses merges que o cadastro não está mais funcionando. Agora o perfil do usuário na hora de fazer cadastro não aparece mais nenhuma opção para usuário escolher e finalizar seu cadastro.

**Comment by LucasAmoedo** [comment]
Prezado caue96,

Agradecemos seu contato. Informamos que a funcionalidade de cadastro está funcionando corretamente até a última build da aplicação. Lembre-se de que a aplicação somente funciona caso seu banco de dados esteja corretamente populado. Sugerimos, então, que realize o seguinte passo a passo:

1. Com um terminal apontando para a pasta de seu Backend, digite `bundle exec rake db:drop`.
2. Em seguida, digite `bundle exec rake db:create`.
3. Digite `mysql -uroot -psuasenha observatorio-devel < db/observatorio_producao.sql`. Aguarde alguns instantes.
4. Digite `bundle exec rake db:migrate`.
5. Verifique se o problema ainda persiste.

Atentamos ao fato de que, atualmente, há dois arquivos com extensão .sql na pasta db de seu backend. Pedimos que não utilize o arquivo banco_observatorio.sql, uma vez que este não possui nenhuma operação de INCLUDE em seu script, e portanto não é capaz de fazer funcionar sua aplicação.

Caso seus problemas persistam, pedimos que nos envie o código de erro retornado por seu terminal do servidor do Rails.

Att.,
Amoêdo

---------------------------------

Lucas Amoêdo
Técnico de Suporte, CodeMitos
lucas_advc@outlook.com
