### ISSUE TITLE
Janelas quebrando no APK

### ISSUE THREAD

**Issue by LucasAmoedo** [fga-gpp-mds/2016.2-Observatorio-de-Residuos-Frontend#72]
O HTML fica estranho no APK. Alguns componentes da tela ficam mal alinhados, e algumas imagens não renderizam. Seguem imagens de exemplo.

![screenshot_20161120-133103](https://cloud.githubusercontent.com/assets/11811420/20463991/083a17c0-af26-11e6-8bb4-f2cdd4fd7173.png)
![screenshot_20161120-133124](https://cloud.githubusercontent.com/assets/11811420/20463992/08ebc542-af26-11e6-86eb-b2328a5da311.png)

**Comment by luizguilherme5** [comment]
Fixed on "Fix image display on android" commid nº 438518217d0febb593ec93aa1856b168ad7d042c
